version: "3.0"

services:
  server:
    container_name: "server"
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - ./audio:/audio
    env_file: .env

  localtunnel:
    container_name: "localtunnel"
    image: efrecon/localtunnel
    restart: on-failure
    command:
      --local-host server --port 80 --subdomain $SUBDOMAIN
    environment:
      - SUBDOMAIN=${SUBDOMAIN}
    links:
      - server
    depends_on:
      - server